# Generated by Django 3.2.8 on 2021-11-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_is_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_employee',
            field=models.BooleanField(null=True),
        ),
    ]
