# Generated by Django 3.2.8 on 2021-11-25 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_is_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='quantity',
        ),
    ]
