# Generated by Django 3.2.8 on 2021-10-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_quanity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quanity',
        ),
    ]
