# Generated by Django 3.2.8 on 2021-10-08 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_delete_quanity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sell',
            options={'ordering': ['time']},
        ),
    ]
