# Generated by Django 3.2.8 on 2021-10-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0006_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='peoduct',
            new_name='product',
        ),
    ]
