# Generated by Django 3.2.8 on 2021-10-12 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0007_rename_peoduct_sale_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='items_sold',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='paid',
        ),
    ]
