# Generated by Django 3.2.8 on 2022-02-13 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0007_remove_product_quantity_after_sale'),
        ('sell', '0008_auto_20211012_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='items_sold',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='product',
        ),
        migrations.AddField(
            model_name='sell',
            name='total_paid',
            field=models.FloatField(default=0, max_length=280),
        ),
        migrations.CreateModel(
            name='SellItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_sold', models.IntegerField()),
                ('paid', models.FloatField(max_length=280)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.product')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.sell')),
            ],
        ),
    ]
