# Generated by Django 3.2.8 on 2022-02-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0009_auto_20220213_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellitem',
            name='sell',
        ),
        migrations.AddField(
            model_name='sell',
            name='sell_items',
            field=models.ManyToManyField(to='sell.SellItem'),
        ),
    ]
