# Generated by Django 3.2.8 on 2021-10-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quantity_after_sale',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_before_sale',
            field=models.IntegerField(default=32),
            preserve_default=False,
        ),
    ]
