# Generated by Django 3.2.8 on 2021-10-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0002_auto_20211007_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='procure_price_per_item',
            field=models.FloatField(default=2.25, max_length=280),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
