# Generated by Django 3.2.8 on 2021-10-08 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0005_auto_20211007_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity_before_sale',
            new_name='quantity',
        ),
    ]
