# Generated by Django 3.2.8 on 2021-11-25 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20211124_0656'),
        ('employees', '0005_remove_employee_quantity'),
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, unique=True)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('checkin_time', models.DateTimeField()),
                ('check_in', models.BooleanField(null=True)),
                ('checkout_time', models.DateTimeField(null=True)),
                ('check_out', models.BooleanField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCheckInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField()),
                ('check_in', models.BooleanField(null=True)),
                ('checkout_time', models.DateTimeField(null=True)),
                ('check_out', models.BooleanField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.product')),
            ],
        ),
        migrations.DeleteModel(
            name='CheckIn',
        ),
    ]
