# Generated by Django 3.2.8 on 2021-11-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_auto_20211125_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcheckinout',
            name='check_out',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcheckinout',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
